name: "[RETAG] VERACIS #tag - $(Build.SourceBranchName) #buildId - $(Build.BuildId)"

trigger: none

variables:
  - name: GIT_TAG
    value: $(Build.SourceBranchName)

pool:
  vmImage: ubuntu-latest

stages:
  - template: templates/approval-gate.yml
    parameters:
      environmentName: testing

  - template: templates/approved-tag.yml
    parameters:
      sourceTag: $(GIT_TAG)
      changedApps: "api, web"
      variableGroups:
        - Veracis-DevOps-Config
      dependsOn:
        - ApprovalGate
      condition: succeeded()

  - template: templates/rejected-tag.yml
    parameters:
      sourceTag: $(GIT_TAG)
      changedApps: "api, web"
      variableGroups:
        - Veracis-DevOps-Config
      dependsOn:
        - ApprovalGate
      condition: failed()
