apiVersion: 1
datasources:
  - name: Mimir
    type: prometheus
    uid: mimir
    url: http://${MIMIR_ENDPOINT}:9009/prometheus
    isDefault: true
    access: proxy
    editable: true
    jsonData:
      timeInterval: "15s"
      prometheusType: Mimir
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo
          urlDisplayLabel: "Ver Trace no Tempo"
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://${TEMPO_ENDPOINT}:3200
    access: proxy
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        filterByTraceID: true
        filterBySpanID: false
        tags:
          - key: "service.name"
            value: "service_name"
        customQuery: false
      tracesToMetrics:
        datasourceUid: mimir
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        tags:
          - key: "service.name"
            value: "service_name"
          - key: "http.route"
            value: "http_route"
        queries:
          - name: "Request Rate"
            query: "sum(rate(http_server_request_duration_seconds_count{$$__tags}[5m]))"
          - name: "Error Rate"
            query: 'sum(rate(http_server_request_duration_seconds_count{$$__tags, http_response_status_code=~"5.."}[5m]))'
          - name: "Latency (p99)"
            query: "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{$$__tags}[5m])) by (le))"
          - name: "Business Flow Duration (p99)"
            query: "histogram_quantile(0.99, sum(rate(business_flow_duration_seconds_bucket{$$__tags}[5m])) by (le, business_flow, business_action))"
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: mimir
      search:
        hide: false
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: "-30m"
        spanEndTimeShift: "30m"
      streamingEnabled:
        search: true
        metrics: true
  - name: Loki
    type: loki
    uid: loki
    url: http://${LOKI_ENDPOINT}:3100
    access: proxy
    editable: true
    jsonData:
      timeout: 60
      maxLines: 1000
      derivedFields:
        - name: traceID
          matcherRegex: '"trace_id":"(\w+)"'
          url: "$${__value.raw}"
          datasourceUid: tempo
          urlDisplayLabel: "Ver Trace no Tempo"
        - name: traceID_camel
          matcherRegex: '"traceId":"(\w+)"'
          url: "$${__value.raw}"
          datasourceUid: tempo
          urlDisplayLabel: "Ver Trace no Tempo"
