export const MAP_ALERT_OPTION_CIRCLE_PX = 80

export const MAP_ALERT_OPTION_ICON_INSET_PX = 2

export const MAP_ALERT_OPTION_ICON_PX =
  MAP_ALERT_OPTION_CIRCLE_PX - 2 * MAP_ALERT_OPTION_ICON_INSET_PX
